apiVersion: v1
kind: Namespace
metadata:
  name: newtest
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: newtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: newtest
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
