apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxcontainers
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linuxcontainers
  template:
    metadata:
      labels:
        app: linuxcontainers
      namespace: wordpress
    spec:
      containers:
      - name: linuxcontainers-container
        image: linuxcontainers/wordpress-php-fpm:latest
        ports:
        - containerPort: 80
