apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch-deployment
labels:
  app: scratch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scratch
  template:
    metadata:
      labels:
        app: scratch
    spec:
      containers:
      - name: scratch-container
        image: scratch:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi