apiVersion: v1
kind: Namespace
metadata:
  name: busytest
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: busytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      namespace: busytest
    spec:
      containers:
      - name: busybox
        image: busybox:1.37.0-musl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: busytest
spec:
  selector:
    app: busybox
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
