apiVersion: v1
kind: Namespace
metadata:
  name: testplat
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: testplat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      namespace: testplat
    spec:
      containers:
      - name: busybox
        image: busybox:1.37.0-uclibc
        imagePullPolicy: Always
