apiVersion: v1
kind: Namespace
metadata:
  name: test123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: test123
    spec:
      containers:
      - name: nginx
        image: harbor.hpe.local:8888/ai-deployments/nginx:latest
        ports:
        - containerPort: 80
