apiVersion: v1
kind: Namespace
metadata:
  name: nginxtest---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginxtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: nginxtest
    spec:
      containers:
      - name: nginx
        image: harbor.hpe.local:8888/platform/nginx:v1
        ports:
        - containerPort: 80
