apiVersion: v1
kind: Namespace
metadata:
  name: debianslim
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-slim
  namespace: debianslim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-slim
  template:
    metadata:
      labels:
        app: debian-slim
      namespace: debianslim
    spec:
      containers:
      - name: debian-slim
        image: linuxcontainers/debian-slim:latest
        ports:
        - containerPort: 80
