apiVersion: v1
kind: Namespace
metadata:
  name: platformtest---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: platformtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      namespace: platformtest
    spec:
      containers:
      - name: busybox
        image: busybox:1.37.0-musl
        imagePullPolicy: Always
