apiVersion: v1
kind: Namespace
metadata:
  name: testns---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: testns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testbug: testbug
      namespace: testns
    spec:
      containers:
      - name: nginx
        image: harbor.hpe.local:8888/platform/nginx:latest
        ports:
        - containerPort: 80
