apiVersion: v1
kind: Namespace
metadata:
  name: busybox
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      namespace: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        ports:
        - containerPort: 80
