apiVersion: v1
kind: Namespace
metadata:
  name: medusa
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8ssandra
  namespace: medusa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8ssandra
  template:
    metadata:
      labels:
        app: k8ssandra
      namespace: medusa
    spec:
      containers:
      - name: k8ssandra
        image: k8ssandra/medusa:0.30.0
        ports:
        - containerPort: 80
