apiVersion: v1
kind: Namespace
metadata:
  name: ns---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: ns
    spec:
      containers:
      - name: nginx:v1
        image: nginx:latest
        ports:
        - containerPort: 80
